package ua.com.mobifix.parser;

import com.github.slugify.Slugify;
import ua.com.mobifix.parser.description.AllSparesDescriptionParser;

import java.util.Locale;
import java.util.Map;


public class test {
    public static void main(String[] args) {
        String html = "<div space=\"page/product-v2/description\" class=\"page_product-v2_description first-no-indents\">  <div space=\"page/product-v2/description/analogues\" class=\"page_product-v2_description_analogues\" name=\"analogues\"> <h2 class=\"mt0\">Похожие товары</h2> <div class=\"page_product-v2_description_analogues_stretch-mobile\"> <section space=\"component/product-list/excel\" class=\"component_product-list_excel\"> <header class=\"component_product-list_excel_header\"> <div class=\"component_product-list_excel_cell component_product-list_excel_id\">ID</div> <div class=\"component_product-list_excel_cell component_product-list_excel_title\">Товар</div> <div class=\"component_product-list_excel_cell component_product-list_excel_regular-price\">Розничная цена <br>  (₴)</div> <div class=\"component_product-list_excel_cell component_product-list_excel_current-price\">Ваша цена <br>  (₴)</div> <div class=\"component_product-list_excel_cell component_product-list_excel_wish-list\"> <a href=\"/ru/account/wishlist/\" key=\"link\">Избранное</a> </div> <div class=\"component_product-list_excel_cell component_product-list_excel_in-stock\">Наличие на складе</div> <div class=\"component_product-list_excel_cell component_product-list_excel_button\">Заказываемое количество</div> </header>  <article space=\"component/product/excel\" class=\"component_product_excel\" key=\"891643\"> <div class=\"component_product_excel_cell component_product_excel_id\"> <span class=\"component_product_excel_id_title\">ID:&nbsp;</span> 891643 </div> <div class=\"component_product_excel_cell component_product_excel_title\"> <a href=\"/ru/housing-back-cover-compatible-with-xiaomi-redmi-note-8-pro-white/\" key=\"link\" title=\"Задняя панель корпуса для Xiaomi Redmi Note 8 Pro, белая, M1906G7I, M1906G7G\" data-from=\"analogue\" name=\"title\">Задняя панель корпуса для Xiaomi Redmi Note 8 Pro, белая, M1906G7I, M1906G7G</a> </div> <div class=\"component_product_excel_cell component_product_excel_regular-price\"><div space=\"component/product/price\" name=\"regular\" key=\"891643\" class=\"product-price\">      <div class=\"-current\">336<span>.00</span></div>      \n" +
                "</div></div> <div class=\"component_product_excel_cell component_product_excel_current-price\">  <div space=\"component/product/price\" name=\"price\" key=\"891643\" class=\"product-price\">      <div class=\"-current\">176<span>.40</span></div>      \n" +
                "</div> <div class=\"component_product_excel_web-price\"> <div space=\"component/product/web-prices\" key=\"891643\" class=\"component_product_web-prices -list hidden tooltipstered\"></div> </div>  </div> <div class=\"component_product_excel_cell component_product_excel_wish-list\"> <div space=\"component/wishlist/btn\" key=\"891643\" class=\"component_wishlist_btn\">  <button type=\"button\" name=\"save\" class=\"component_wishlist_btn_btn\"> <span class=\"component_wishlist_btn_btn_text\"> <i class=\"icon-wishlist\"></i> <span class=\"component_wishlist_btn_title\">  В избранное  </span> </span> </button> \n" +
                "</div> </div> <div class=\"component_product_excel_cell component_product_excel_in-stock\"><div space=\"component/product/in-stock\" class=\"component_product_in-stock prp_info_item tooltipstered\"> <span class=\"component_product_in-stock_title\"> Наличие на складе:\n" +
                "    </span> <span data-tooltip=\"\">  <i class=\"component_product_in-stock_in-stock\">К</i>  <i class=\"component_product_in-stock_in-stock\">Л</i>  <i class=\"component_product_in-stock_in-stock\">Ц</i>  <i class=\"component_product_in-stock_in-stock\">Р</i>  <i class=\"component_product_in-stock_in-stock\">П</i>  <i class=\"component_product_in-stock_in-stock\">Ч</i>  </span>\n" +
                "</div><div space=\"component/product/in-stock-type-2\" class=\"component_product_in-stock-type-2 type-2\"> <span class=\"title\">Наличие на складе:</span> <ul class=\"stocks\">  <li>Киев</li>  <li>Львов</li>  <li>Центральный</li>  <li>Ровно</li>  <li>Полтава</li>  <li>Черкассы</li>  </ul>\n" +
                "</div></div> <div class=\"component_product_excel_cell component_product_excel_button\"><div space=\"component/product/btn\" key=\"891643\" class=\"component_product_btn product-btn\">   <button type=\"button\" name=\"create\" class=\"btn btn-buy btn--add-to-cart\"> В корзину </button>  <div class=\"btn--in-cart hidden\"> <button type=\"button\" name=\"minus\" class=\"btn\"></button> <div class=\"quantity-input\"> <input name=\"quantity\" type=\"text\" autocomplete=\"off\" value=\"\"> </div> <button type=\"button\" name=\"plus\" class=\"btn\"></button>   <div class=\"under-text\">шт. в <a href=\"/ru/cart/\" key=\"link\">Корзине</a></div>   </div> \n" +
                "</div>\n" +
                "</div>\n" +
                "</article>  <article space=\"component/product/excel\" class=\"component_product_excel\" key=\"891644\"> <div class=\"component_product_excel_cell component_product_excel_id\"> <span class=\"component_product_excel_id_title\">ID:&nbsp;</span> 891644 </div> <div class=\"component_product_excel_cell component_product_excel_title\"> <a href=\"/ru/housing-back-cover-compatible-with-xiaomi-redmi-note-8-pro-green/\" key=\"link\" title=\"Задняя панель корпуса для Xiaomi Redmi Note 8 Pro, зеленая, M1906G7I, M1906G7G\" data-from=\"analogue\" name=\"title\">Задняя панель корпуса для Xiaomi Redmi Note 8 Pro, зеленая, M1906G7I, M1906G7G</a> </div> <div class=\"component_product_excel_cell component_product_excel_regular-price\"><div space=\"component/product/price\" name=\"regular\" key=\"891644\" class=\"product-price\">      <div class=\"-current\">336<span>.00</span></div>      \n" +
                "</div></div> <div class=\"component_product_excel_cell component_product_excel_current-price\">  <div space=\"component/product/price\" name=\"price\" key=\"891644\" class=\"product-price\">      <div class=\"-current\">176<span>.40</span></div>      \n" +
                "</div> <div class=\"component_product_excel_web-price\"> <div space=\"component/product/web-prices\" key=\"891644\" class=\"component_product_web-prices -list hidden tooltipstered\"></div> </div>  </div> <div class=\"component_product_excel_cell component_product_excel_wish-list\"> <div space=\"component/wishlist/btn\" key=\"891644\" class=\"component_wishlist_btn\">  <button type=\"button\" name=\"save\" class=\"component_wishlist_btn_btn\"> <span class=\"component_wishlist_btn_btn_text\"> <i class=\"icon-wishlist\"></i> <span class=\"component_wishlist_btn_title\">  В избранное  </span> </span> </button> \n" +
                "</div> </div> <div class=\"component_product_excel_cell component_product_excel_in-stock\"><div space=\"component/product/in-stock\" class=\"component_product_in-stock prp_info_item tooltipstered\"> <span class=\"component_product_in-stock_title\"> Наличие на складе:\n" +
                "    </span> <span data-tooltip=\"\">  <i class=\"component_product_in-stock_in-stock\">Л</i>  <i class=\"component_product_in-stock_in-stock\">Х</i>  <i class=\"component_product_in-stock_in-stock\">Д</i>  <i class=\"component_product_in-stock_in-stock\">Ц</i>  <i class=\"component_product_in-stock_in-stock\">Р</i>  <i class=\"component_product_in-stock_in-stock\">П</i>  <i class=\"component_product_in-stock_in-stock\">О</i>  <i class=\"component_product_in-stock_in-stock\">Ч</i>  <i class=\"component_product_in-stock_in-stock\">ІФ</i>  </span>\n" +
                "</div><div space=\"component/product/in-stock-type-2\" class=\"component_product_in-stock-type-2 type-2\"> <span class=\"title\">Наличие на складе:</span> <ul class=\"stocks\">  <li>Харьков</li>  <li>Львов</li>  <li>Днепр</li>  <li>Центральный</li>  <li>Ровно</li>  <li>Полтава</li>  <li>Одесса</li>  <li>Черкассы</li>  <li>Ивано-Франковск</li>  </ul>\n" +
                "</div></div> <div class=\"component_product_excel_cell component_product_excel_button\"><div space=\"component/product/btn\" key=\"891644\" class=\"component_product_btn product-btn\">   <button type=\"button\" name=\"create\" class=\"btn btn-buy btn--add-to-cart\"> В корзину </button>  <div class=\"btn--in-cart hidden\"> <button type=\"button\" name=\"minus\" class=\"btn\"></button> <div class=\"quantity-input\"> <input name=\"quantity\" type=\"text\" autocomplete=\"off\" value=\"\"> </div> <button type=\"button\" name=\"plus\" class=\"btn\"></button>   <div class=\"under-text\">шт. в <a href=\"/ru/cart/\" key=\"link\">Корзине</a></div>   </div> \n" +
                "</div>\n" +
                "</div>\n" +
                "</article>  <article space=\"component/product/excel\" class=\"component_product_excel\" key=\"891645\"> <div class=\"component_product_excel_cell component_product_excel_id\"> <span class=\"component_product_excel_id_title\">ID:&nbsp;</span> 891645 </div> <div class=\"component_product_excel_cell component_product_excel_title\"> <a href=\"/ru/housing-back-cover-compatible-with-xiaomi-redmi-note-8-pro-dark-blue/\" key=\"link\" title=\"Задняя панель корпуса для Xiaomi Redmi Note 8 Pro, синяя, M1906G7I, M1906G7G\" data-from=\"analogue\" name=\"title\">Задняя панель корпуса для Xiaomi Redmi Note 8 Pro, синяя, M1906G7I, M1906G7G</a> </div> <div class=\"component_product_excel_cell component_product_excel_regular-price\"><div space=\"component/product/price\" name=\"regular\" key=\"891645\" class=\"product-price\">      <div class=\"-current\">336<span>.00</span></div>      \n" +
                "</div></div> <div class=\"component_product_excel_cell component_product_excel_current-price\">  <div space=\"component/product/price\" name=\"price\" key=\"891645\" class=\"product-price\">      <div class=\"-current\">176<span>.40</span></div>      \n" +
                "</div> <div class=\"component_product_excel_web-price\"> <div space=\"component/product/web-prices\" key=\"891645\" class=\"component_product_web-prices -list hidden tooltipstered\"></div> </div>  </div> <div class=\"component_product_excel_cell component_product_excel_wish-list\"> <div space=\"component/wishlist/btn\" key=\"891645\" class=\"component_wishlist_btn\">  <button type=\"button\" name=\"save\" class=\"component_wishlist_btn_btn\"> <span class=\"component_wishlist_btn_btn_text\"> <i class=\"icon-wishlist\"></i> <span class=\"component_wishlist_btn_title\">  В избранное  </span> </span> </button> \n" +
                "</div> </div> <div class=\"component_product_excel_cell component_product_excel_in-stock\"><div space=\"component/product/in-stock\" class=\"component_product_in-stock prp_info_item tooltipstered\"> <span class=\"component_product_in-stock_title\"> Наличие на складе:\n" +
                "    </span> <span data-tooltip=\"\">  <i class=\"component_product_in-stock_in-stock\">К</i>  <i class=\"component_product_in-stock_in-stock\">Х</i>  <i class=\"component_product_in-stock_in-stock\">Д</i>  <i class=\"component_product_in-stock_in-stock\">Ц</i>  <i class=\"component_product_in-stock_in-stock\">Р</i>  <i class=\"component_product_in-stock_in-stock\">П</i>  <i class=\"component_product_in-stock_in-stock\">О</i>  <i class=\"component_product_in-stock_in-stock\">Ч</i>  <i class=\"component_product_in-stock_in-stock\">ІФ</i>  </span>\n" +
                "</div><div space=\"component/product/in-stock-type-2\" class=\"component_product_in-stock-type-2 type-2\"> <span class=\"title\">Наличие на складе:</span> <ul class=\"stocks\">  <li>Киев</li>  <li>Харьков</li>  <li>Днепр</li>  <li>Центральный</li>  <li>Ровно</li>  <li>Полтава</li>  <li>Одесса</li>  <li>Черкассы</li>  <li>Ивано-Франковск</li>  </ul>\n" +
                "</div></div> <div class=\"component_product_excel_cell component_product_excel_button\"><div space=\"component/product/btn\" key=\"891645\" class=\"component_product_btn product-btn\">   <button type=\"button\" name=\"create\" class=\"btn btn-buy btn--add-to-cart\"> В корзину </button>  <div class=\"btn--in-cart hidden\"> <button type=\"button\" name=\"minus\" class=\"btn\"></button> <div class=\"quantity-input\"> <input name=\"quantity\" type=\"text\" autocomplete=\"off\" value=\"\"> </div> <button type=\"button\" name=\"plus\" class=\"btn\"></button>   <div class=\"under-text\">шт. в <a href=\"/ru/cart/\" key=\"link\">Корзине</a></div>   </div> \n" +
                "</div>\n" +
                "</div>\n" +
                "</article>  <article space=\"component/product/excel\" class=\"component_product_excel\" key=\"899412\"> <div class=\"component_product_excel_cell component_product_excel_id\"> <span class=\"component_product_excel_id_title\">ID:&nbsp;</span> 899412 </div> <div class=\"component_product_excel_cell component_product_excel_title\"> <a href=\"/ru/housing-back-cover-compatible-with-xiaomi-redmi-note-8-pro-orange-m1906g7i-m1906g7g/\" key=\"link\" title=\"Задняя панель корпуса для Xiaomi Redmi Note 8 Pro, оранжевая, M1906G7I, M1906G7G\" data-from=\"analogue\" name=\"title\">Задняя панель корпуса для Xiaomi Redmi Note 8 Pro, оранжевая, M1906G7I, M1906G7G</a> </div> <div class=\"component_product_excel_cell component_product_excel_regular-price\"><div space=\"component/product/price\" name=\"regular\" key=\"899412\" class=\"product-price\">      <div class=\"-current\">336<span>.00</span></div>      \n" +
                "</div></div> <div class=\"component_product_excel_cell component_product_excel_current-price\">  <div space=\"component/product/price\" name=\"price\" key=\"899412\" class=\"product-price\">      <div class=\"-current\">176<span>.40</span></div>      \n" +
                "</div> <div class=\"component_product_excel_web-price\"> <div space=\"component/product/web-prices\" key=\"899412\" class=\"component_product_web-prices -list hidden tooltipstered\"></div> </div>  </div> <div class=\"component_product_excel_cell component_product_excel_wish-list\"> <div space=\"component/wishlist/btn\" key=\"899412\" class=\"component_wishlist_btn\">  <button type=\"button\" name=\"save\" class=\"component_wishlist_btn_btn\"> <span class=\"component_wishlist_btn_btn_text\"> <i class=\"icon-wishlist\"></i> <span class=\"component_wishlist_btn_title\">  В избранное  </span> </span> </button> \n" +
                "</div> </div> <div class=\"component_product_excel_cell component_product_excel_in-stock\"><div space=\"component/product/in-stock\" class=\"component_product_in-stock prp_info_item tooltipstered\"> <span class=\"component_product_in-stock_title\"> Наличие на складе:\n" +
                "    </span> <span data-tooltip=\"\">  <i class=\"component_product_in-stock_in-stock\">К</i>  <i class=\"component_product_in-stock_in-stock\">Л</i>  <i class=\"component_product_in-stock_in-stock\">Ц</i>  <i class=\"component_product_in-stock_in-stock\">Р</i>  <i class=\"component_product_in-stock_in-stock\">П</i>  <i class=\"component_product_in-stock_in-stock\">О</i>  <i class=\"component_product_in-stock_in-stock\">Ч</i>  <i class=\"component_product_in-stock_in-stock\">ІФ</i>  </span>\n" +
                "</div><div space=\"component/product/in-stock-type-2\" class=\"component_product_in-stock-type-2 type-2\"> <span class=\"title\">Наличие на складе:</span> <ul class=\"stocks\">  <li>Киев</li>  <li>Львов</li>  <li>Центральный</li>  <li>Ровно</li>  <li>Полтава</li>  <li>Одесса</li>  <li>Черкассы</li>  <li>Ивано-Франковск</li>  </ul>\n" +
                "</div></div> <div class=\"component_product_excel_cell component_product_excel_button\"><div space=\"component/product/btn\" key=\"899412\" class=\"component_product_btn product-btn\">   <button type=\"button\" name=\"create\" class=\"btn btn-buy btn--add-to-cart\"> В корзину </button>  <div class=\"btn--in-cart hidden\"> <button type=\"button\" name=\"minus\" class=\"btn\"></button> <div class=\"quantity-input\"> <input name=\"quantity\" type=\"text\" autocomplete=\"off\" value=\"\"> </div> <button type=\"button\" name=\"plus\" class=\"btn\"></button>   <div class=\"under-text\">шт. в <a href=\"/ru/cart/\" key=\"link\">Корзине</a></div>   </div> \n" +
                "</div>\n" +
                "</div>\n" +
                "</article> \n" +
                "</section>  </div>\n" +
                "</div>   <p class=\"head-text\">Задняя панель корпуса подходит к следующим моделям мобильных телефонов:</p> <ul>  <li>Xiaomi Redmi Note 8 Pro</li>  </ul>   <p class=\"head-text\">Цвет задней панели корпуса:</p>  <ul><li>Черный</li></ul>    <h3>Вас также могут заинтересовать товары из следующих категорий:</h3>  <ul> <li><a href=\"/ru/spares/flat-cables/\" key=\"link\">Шлейфы</a></li> </ul>  <ul> <li><a href=\"/ru/spares/lcd/\" key=\"link\">Дисплеи</a></li> </ul>  <ul> <li><a href=\"/ru/spares/housings-and-accessories/sim-card-holders/\" key=\"link\">Держатели SIM-карты</a></li> </ul>   \n" +
                "</div>";
        AllSparesDescriptionParser allSparesDescriptionParser = new AllSparesDescriptionParser();
        allSparesDescriptionParser.parseHtmlToJson(html);
    }
}
